# -*- coding: utf-8 -*-
"""OCR Basics-EasyOCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o5YcROopsIDYUp2PW4RdMVsNa31nV5Fs

## 0. Install and Import Dependencies
"""

# Install pytorch
#https://pytorch.org/get-started/locally/
#!pip3 install torch torchvision torchaudio
# Install easyocr
#!pip install easyocr

import easyocr
import cv2
from matplotlib import pyplot as plt
import numpy as np

"""## 1. Read in images or video"""

def image_read(image_path):
  reader = easyocr.Reader(['en'])
  result = reader.readtext(IMAGE_PATH)
  return result

def image_show(result, image_path):
  img = cv2.imread(image_path)
  spacer = 100
  text = ""
  for detection in result:
      top_left = tuple(detection[0][0])
      bottom_right = tuple(detection[0][2])
      text = detection[1]
      img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),3)
      spacer+=15

  plt.imshow(img)
  plt.show()

  return text

IMAGE_PATH = '/content/ertrytjrt.jpg'
result = image_read(IMAGE_PATH)
image_show(result, IMAGE_PATH)

"""## 3. GUI

"""

!apt-get install -y xvfb python-opengl
!pip install pyvirtualdisplay pillow

from pyvirtualdisplay import Display

# Start virtual display
display = Display(visible=0, size=(800, 600))
display.start()

import tkinter as tk
from tkinter import filedialog
from pyvirtualdisplay import Display
from PIL import Image, ImageGrab
from IPython.display import display as ipy_display, Image as IPyImage

class FileSelectorApp:
    def __init__(self):
        # Start a virtual display
        self.display = Display(visible=0, size=(800, 600))
        self.display.start()

        # Initialize the main Tkinter window
        self.root = tk.Tk()
        self.root.withdraw()  # Hide the main window

        # Run the file selection process
        # self.select_file()

    def select_file(self):
        # Open file dialog to select a file
        file_path = filedialog.askopenfilename(title="Select a File")

        # Check if a file was selected
        if file_path:
            # Create a new window to display the file path
            self.root.deiconify()  # Show the window
            self.root.geometry("400x200")
            label = tk.Label(self.root, text=f"Selected File: {file_path}", wraplength=350)
            label.pack(pady=20)
            self.root.update()

            # Capture the Tkinter window as an image
            x = self.root.winfo_rootx()
            y = self.root.winfo_rooty()
            x1 = x + self.root.winfo_width()
            y1 = y + self.root.winfo_height()
            img = ImageGrab.grab((x, y, x1, y1))

            # Save and display the image in Colab
            img.save("selected_file.png")
            ipy_display(IPyImage("selected_file.png"))
        else:
            print("No file selected")

        # Destroy the Tkinter window
        self.root.destroy()

    def __del__(self):
        # Stop the virtual display when done
        self.display.stop()

# Run the application
app = FileSelectorApp()
